### PR TITLE
Development

### PR DESCRIPTION
**Pull request by sanjida-sultana**
I am updating index.html to index.php for making login and signup page.and added a sql file for login page on development branch I did not push it to main because I am still working on it

### CODE REVIEW

**Comment by blurple9999** [comment]
Do not push product.php if no changes are made to it. It will only complicate future issues with needing to update that file.

**Comment by sanjida-sultana** [comment]
ok but curently I am working with index to connect with login to home.we need to add index.php url to header in product.php

**Comment by sanjida-sultana** [comment]
if u check it tomorrow then you will find it I will pust index.php tomorrow. I am still working on it.I am not making any changes to product just change the header index.php

**Comment by blurple9999** [comment]
I know you arent intending to make any changes to product.php, but github is showing a confliction with it from somewhere. Pull the product.php from main into dev branch to fix the conflict.

**Pull request closed without merging**
