### PR TITLE
Development

### PR DESCRIPTION
**Pull request by MehediZihad**
Check the merge

### CODE REVIEW

**Comment by blurple9999** [comment]
product.php looks to be good, i approve its merge, but ask someone else to merge it if it looks good, i cannot comment on the other files

**Comment by MehediZihad** [comment]
okay. Thanks

**Comment by sanjida-sultana** [comment]
I saw a conflict u have to do a git pull from origin main then checkout development then git merge main and then push -u origin development to resolve the conflict

**Comment by MehediZihad** [comment]
I did.

**Pull request closed without merging**
